--============================================================================================
-- some configuration of sqlplus -- A SWEET DISPLAY xD
--============================================================================================
set line 10000;
set pages 200;
SET SERVEROUTPUT ON
COLUMN REFERENCES  FORMAT A23
COLUMN OLDVALUES  FORMAT A15
COLUMN SYNTACTICTYPE  FORMAT A15
COLUMN COLUMNWIDHT  FORMAT 99
COLUMN NUMBEROFWORDS  FORMAT 99
COLUMN OBSERVATION FORMAT A25
COLUMN REGULAREXPR FORMAT A60
COLUMN SEMANTICCATEGORY FORMAT A20
COLUMN NEWVALUES FORMAT A25
COLUMN SEMANTICSUBCATEGORY FORMAT A20
COLUMN SUBCATEGORY FORMAT A15



COLUMN CSVFILE FORMAT A30
COLUMN DR_CSVFILE_COL1  FORMAT A10
COLUMN DR_CSVFILE_COL2 FORMAT A10
COLUMN DR_CSVFILE_COL3 FORMAT A10
COLUMN DR_CSVFILE_COL4 FORMAT A10
COLUMN DR_CSVFILE_COL5 FORMAT A10
COLUMN DR_CSVFILE_COL6 FORMAT A10

COLUMN COL1 FORMAT A10
COLUMN COL2 FORMAT A10
COLUMN COL3 FORMAT A10
COLUMN COL4 FORMAT A15
COLUMN COL5 FORMAT A20
COLUMN COL6 FORMAT A5
COLUMN COL7 FORMAT A5
COLUMN COL8 FORMAT A10
COLUMN COL9 FORMAT A10
COLUMN COL10 FORMAT A10
COLUMN COL11 FORMAT A10
COLUMN COL12 FORMAT A10
COLUMN COL13 FORMAT A10