CREATE TABLE ETUDIUTV(
  ID VARCHAR2(20),
  NOM VARCHAR2(30),
  PRENOM VARCHAR2(30),
  DATEN DATE,
  VILLE VARCHAR2(30),
  PAYS VARCHAR2(30)
);

CREATE TABLE ETUDIG(
  NUME VARCHAR2(20),
  NOME VARCHAR2(30),
  PRENE VARCHAR2(30),
  DN DATE,
  VIL VARCHAR2(30),
  PAY VARCHAR2(30)
);

INSERT INTO ETUDIUTV(ID, NOM, PRENOM, DATEN, VILLE, PAYS)
VALUES ('i1', 'LE BON', 'Adam',  '19-JUN-2001', 'Epinay sur seine', 'France');

INSERT INTO ETUDIUTV(ID, NOM, PRENOM, DATEN, VILLE, PAYS)
VALUES ('i2', 'BELLE', 'Clemence',  '16-NOV-1996', 'Nice', 'France');

INSERT INTO ETUDIUTV(ID, NOM, PRENOM, DATEN, VILLE, PAYS)
VALUES ('i3', 'BELLE', 'C.',  '16-NOV-1996', 'Nice', 'France');


INSERT INTO ETUDIG(NUME, NOME, PRENE, DN, VIL, PAY)
VALUES ('g1', 'LE BON', 'Adem',  '19-JUN-2001', 'Epinay-sur-seine', 'France');

INSERT INTO ETUDIG(NUME, NOME, PRENE, DN, VIL, PAY)
VALUES ('g2', 'LEBON', 'Adams',  '19-JUN-2001', 'Epinay-sur-seine', 'France');
