-- ===============================================================================
-------- Université Sorbonne Paris Cité, Université Paris 13 , Institut Galiée
-------- Master 2 (M2 EID2), Informatique, Ingénieur
-------- Exploration Informatique des Données et Décisionnel
-- ===============================================================================
-------- La Data ; The Data
-------- La Donnée est le monde du futur ; Les données et le monde de l'avenir
-------- The Data is the world of the future ;  The Data and the future's world

-------- DATA -->>> Big Data, Dark Data, Open Data, ... 
-- ===============================================================================
-------- Bases de Données Avancées = Advanced Databases (BDA)
-------- Entrepôts de Données = Data Warehouses (DWH, EDON)
-------- Lacs de Données = Data Lakes (LD, DL)


-------- Directeur :  Dr. M. Faouzi Boufarès (MFB)
-------- Enseignant-Chercheur Responsable      

-------- Page Web : http://www.lipn.univ-paris13.fr/~boufares

-- ===============================================================================
-------- http://www.lipn.univ-paris13.fr/~boufares/Master2/*.sql
-- ===============================================================================
--   Projet  BDM : Big Data Management - Gestion des Données Massives
--
--   Data Manipulation (DM) - Manipulation de Données
--   Data Integration (DI) - Intégration de Données
--   Données structurées ; Données Semi-structurées ; Données NON structurées
--   Structured data; Semi-structured data; NON-structured data

--   Master Data Management (MDM) - Gestion des Données de Référence
--   Data Quality Managment (DQM) - Gestion de la qualité des données
--   Data Cleaning - Nettayage des données
--   Data deduplication - Elimination des doubles et des similaires

--   More semantics to better correct the data 
--   Plus de sémantique afin de mieux corriger les données
-- ===============================================================================
-- ===============================================================================
--
--------=============  BIG DATA, DATA BASE, DATA WAREHOUSE =============----------
--
-- Big Data & Clound Computing : Think DIFFERENTLY, BIGGER and SMARTER !
-- The Excellence in Data Use !
-- EID : L'Excellence dans l'Investigation des Données
-- EID : Excellence in Data Investigation
--
-- =============================================================================== 
-- Think DIFFERENTLY, BIGGER and SMARTER ! The Excellence in Data Use !
-- MISSION IMPOSSIBLE OU POSSIBLE ????? !!!!!!!!!!!
-- Votre mission, si vous l'acceptez, est : The Excellence in Data Use !
-- Si vous échouez, nous nierons avoir eu connaissance de vos agissements !

-- ===============================================================================
-- Les dictons du jour !
--
-- Aujourd'hui, j'arrête de fumer
-- Le TABAC t'ABAT
-- Fumer nuit grâvement à ta santé et à celle de ton entourage
--
-- M   T   Dents
-- SMILE and the World SMILES with you !
--
-- MANGER + MANGER = GROSSIR (??? M, A, N, G, E, R, O, S, S, I)
--
-- Manger & Bouger, 
-- Pour votre santé mangez 5 fruits et légumes par jour
-- Pour votre santé ne mangez pas trop gras, trop salé, trop sucré
-- Pour votre santé faites une activité physique régulière
-- Pour votre santé faites 30 mn de marche par jour
-- Pour votre santé faites des BD !!!
--
-- Dr. M. Faouzi Boufarès
-- =============================================================================== 
-- =============================================================================== 
--   A new ETL   ETL & DQ : Extract-Transform-Load & Data-Quality 
--                    Al ETL Al Jadyd   
-- ===============================================================================
-- ===============================================================================

-- =============================================================================== 
-- =============================================================================== 
-- ===============================================================================                   
--   Nom du SGBD/DBMS  : ORACLE  /  DB2  /  MySQL  /  ...        
--   Date de creation  : 14/11/2019
---  Lieu              : Université Sorbonne Paris Cité, Université Paris 13, Institut Galiée
-- =============================================================================== 

-- MFB MFB MFB MFB MFB MFB MFB MFB MFB
-- ===============================================================================

-- Data Dictionnary for valid strings
-- Creation of data structure

CREATE TABLE DDVS 
(
CATEGORY VARCHAR(50), 
ENGLISH VARCHAR(100), 
FRENCH VARCHAR(100),          -- Autant de langues que nécessaire
ABREVGENDEROTHER VARCHAR(50), -- Considéré comme une langue English ou French
PRIMARYKEY VARCHAR(50), 
FOREIGNKEY VARCHAR(50), 
CONSTRAINT PKDDVS PRIMARY KEY (PRIMARYKEY) 
);

INSERT INTO DDVS VALUES ('CONTINENT', 'AFRICA', 'AFRIQUE', 'AF', 'CONTINENT01', '');
INSERT INTO DDVS VALUES ('CONTINENT', 'AMERICA', 'AMÉRIQUE', 'AM', 'CONTINENT02', '');
INSERT INTO DDVS VALUES ('CONTINENT', 'ASIA', 'ASIE', 'AS', 'CONTINENT03', '');
INSERT INTO DDVS VALUES ('CONTINENT', 'EUROPE', 'EUROPE', 'EU', 'CONTINENT04', '');
INSERT INTO DDVS VALUES ('CONTINENT', 'OCEANIA', 'OCÉANIE', 'OC', 'CONTINENT05', '');
COMMIT;
INSERT INTO DDVS VALUES ('CONTINENT', 'Antarctica', 'Antarctique', 'AN', 'CONTINENT06', '');
INSERT INTO DDVS VALUES ('COUNTRY', 'SOUTH-AFRICA', 'AFRIQUE-DU-SUD', '', 'CONTINENT01COUNTRY001', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'ALGERIA', 'ALGÉRIE', '', 'CONTINENT01COUNTRY002', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'ANGOLA', 'ANGOLA', '', 'CONTINENT01COUNTRY003', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'BENIN', 'BÉNIN', '', 'CONTINENT01COUNTRY004', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'BOTSWANA', 'BOTSWANA', '', 'CONTINENT01COUNTRY005', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'BURKINA-FASO', 'BURKINA-FASO', '', 'CONTINENT01COUNTRY006', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'BURUNDI', 'BURUNDI', '', 'CONTINENT01COUNTRY007', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'CAMEROON', 'CAMEROUN', '', 'CONTINENT01COUNTRY008', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'CAPE-VERDE', 'CAP-VERT', '', 'CONTINENT01COUNTRY009', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'COMOROS', 'COMORES', '', 'CONTINENT01COUNTRY010', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'IVORY-COAST', 'CÔTE-D''IVOIRE', '', 'CONTINENT01COUNTRY011', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'DJIBOUTI', 'DJIBOUTI', '', 'CONTINENT01COUNTRY012', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'EGYPT', 'EGYPTE', '', 'CONTINENT01COUNTRY013', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'ETHIOPIA', 'ETHIOPIE', '', 'CONTINENT01COUNTRY014', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'GABON', 'GABON', '', 'CONTINENT01COUNTRY015', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'GAMBIA', 'GAMBIE', '', 'CONTINENT01COUNTRY016', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'GHANA', 'GHANA', '', 'CONTINENT01COUNTRY017', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUINEA', 'GUINÉE', '', 'CONTINENT01COUNTRY018', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUINEA-BISSAU', 'GUINÉE-BISSAU', '', 'CONTINENT01COUNTRY019', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'EQUATORIAL-GUINEA', 'GUINÉE-EQUATORIALE', '', 'CONTINENT01COUNTRY020', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'KENYA', 'KENYA', '', 'CONTINENT01COUNTRY021', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'LESOTHO', 'LESOTHO', '', 'CONTINENT01COUNTRY022', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'LIBERIA', 'LIBÉRIA', '', 'CONTINENT01COUNTRY023', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'LYBIA', 'LYBIE', '', 'CONTINENT01COUNTRY024', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'MADAGASCAR', 'MADAGASCAR', '', 'CONTINENT01COUNTRY025', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'MALAWI', 'MALAWI', '', 'CONTINENT01COUNTRY026', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'MOROCCO', 'MAROC', '', 'CONTINENT01COUNTRY027', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'MAURITIUS', 'MAURICE', '', 'CONTINENT01COUNTRY028', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'MAURITANIA', 'MAURITANIE', '', 'CONTINENT01COUNTRY029', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'MOZAMBIQUE', 'MOZAMBIQUE', '', 'CONTINENT01COUNTRY030', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'NAMIBIA', 'NAMIBIE', '', 'CONTINENT01COUNTRY031', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'NIGER', 'NIGER', '', 'CONTINENT01COUNTRY032', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'NIGERIA', 'NIGERIA', '', 'CONTINENT01COUNTRY033', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'UGANDA', 'OUGANDA', '', 'CONTINENT01COUNTRY034', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'DEMOCRATIC-REPUBLIC-OF-CONGO', 'RÉPUBLIQUE-DÉMOCRATIQUE-DU-CONGO', '', 'CONTINENT01COUNTRY035', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'REPUBLIC-OF-CONGO', 'RÉPUBLIQUE-DU-CONGO', '', 'CONTINENT01COUNTRY036', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'RWANDA', 'RWANDA', '', 'CONTINENT01COUNTRY037', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAO-TOMÉ-AND-PRINCIPLE', 'SAO-TOMÉ-ET-PRINCIPE', '', 'CONTINENT01COUNTRY038', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SENEGAL', 'SÉNÉGAL', '', 'CONTINENT01COUNTRY039', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SEYCHELLES', 'SEYCHELLES', '', 'CONTINENT01COUNTRY040', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SIERRA-LEONE', 'SIERRA-LEONE', '', 'CONTINENT01COUNTRY041', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SOMALIA', 'SOMALIE', '', 'CONTINENT01COUNTRY042', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SUDAN', 'SOUDAN', '', 'CONTINENT01COUNTRY043', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'SWAZILAND', 'SWAZILAND', '', 'CONTINENT01COUNTRY044', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'TANZANIA', 'TANZANIE', '', 'CONTINENT01COUNTRY045', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'CHAD', 'TCHAD', '', 'CONTINENT01COUNTRY046', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'TOGO', 'TOGO', '', 'CONTINENT01COUNTRY047', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'TUNISIA', 'TUNISIE', '', 'CONTINENT01COUNTRY048', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'ZIMBABWE', 'ZIMBABWE', '', 'CONTINENT01COUNTRY049', 'CONTINENT01');
INSERT INTO DDVS VALUES ('COUNTRY', 'ALASKA', 'ALASKA', '', 'CONTINENT02COUNTRY001', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'ANGUILLA', 'ANGUILLA', '', 'CONTINENT02COUNTRY002', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'ANTIGUA-AND-BARBUDA', 'ANTIGUA-ET-BARBUDA', '', 'CONTINENT02COUNTRY003', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'DUTCH-ANTILLES', 'ANTILLES-NÉERLANDAISES', '', 'CONTINENT02COUNTRY004', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'ARGENTINA', 'ARGENTINE', '', 'CONTINENT02COUNTRY005', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'ARUBA', 'ARUBA', '', 'CONTINENT02COUNTRY006', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BAHAMAS', 'BAHAMAS', '', 'CONTINENT02COUNTRY007', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BARBADIA', 'BARBADE', '', 'CONTINENT02COUNTRY008', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BELIZE', 'BELIZE', '', 'CONTINENT02COUNTRY009', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BERMUDES', 'BERMUDES', '', 'CONTINENT02COUNTRY010', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BOLIVIA', 'BOLIVIE', '', 'CONTINENT02COUNTRY011', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BRAZIL', 'BRÉSIL', '', 'CONTINENT02COUNTRY012', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'CANADA', 'CANADA', '', 'CONTINENT02COUNTRY013', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'CHILE', 'CHILI', '', 'CONTINENT02COUNTRY014', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'COLOMBIA', 'COLOMBIE', '', 'CONTINENT02COUNTRY015', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'COSTA-RICA', 'COSTA-RICA', '', 'CONTINENT02COUNTRY016', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'CUBA', 'CUBA', '', 'CONTINENT02COUNTRY017', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'DOMINIQUE', 'DOMINIQUE', '', 'CONTINENT02COUNTRY018', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'ECUADOR', 'ÉQUATEUR', '', 'CONTINENT02COUNTRY019', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'UNITED-STATES-OF-AMERICA', 'ÉTATS-UNIS-D''AMÉRIQUE', '', 'CONTINENT02COUNTRY020', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SANDWICH-ISLANDS', 'ILES-SANDWICH', '', 'CONTINENT02COUNTRY021', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'GRENADA', 'GRENADE', '', 'CONTINENT02COUNTRY022', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'GREENLAND', 'GROENLAND', '', 'CONTINENT02COUNTRY023', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUADELOUPE', 'GUADELOUPE', '', 'CONTINENT02COUNTRY024', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUATEMALA', 'GUATEMALA', '', 'CONTINENT02COUNTRY025', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUYANA', 'GUYANA', '', 'CONTINENT02COUNTRY026', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUYANA', 'GUYANE', '', 'CONTINENT02COUNTRY027', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'HAITI', 'HAÏTI', '', 'CONTINENT02COUNTRY028', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'HONDURAS', 'HONDURAS', '', 'CONTINENT02COUNTRY029', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'JAMAICA', 'JAMAÏQUE', '', 'CONTINENT02COUNTRY030', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'MALWAYS', 'MALOUINES', '', 'CONTINENT02COUNTRY031', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'MARTINIQUE', 'MARTINIQUE', '', 'CONTINENT02COUNTRY032', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'MEXICO', 'MEXIQUE', '', 'CONTINENT02COUNTRY033', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'MONTSERRAT', 'MONTSERRAT', '', 'CONTINENT02COUNTRY034', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'NICARAGUA', 'NICARAGUA', '', 'CONTINENT02COUNTRY035', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'PANAMA', 'PANAMA', '', 'CONTINENT02COUNTRY036', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'PARAGUAY', 'PARAGUAY', '', 'CONTINENT02COUNTRY037', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'PERU', 'PÉROU', '', 'CONTINENT02COUNTRY038', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'PORTO-RICO', 'PORTO-RICO', '', 'CONTINENT02COUNTRY039', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'DOMINICAN-REPUBLIC', 'RÉPUBLIQUE-DOMINICAINE', '', 'CONTINENT02COUNTRY040', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-BARTHÉLEMY', 'SAINT-BARTHÉLEMY', '', 'CONTINENT02COUNTRY041', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-CHRISTOPHER-AND-NEVIS', 'SAINT-CHRISTOPHE-ET-NIÉVÈS', '', 'CONTINENT02COUNTRY042', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINTE-LUCIE', 'SAINTE-LUCIE', '', 'CONTINENT02COUNTRY043', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-MARTIN-(FR)', 'SAINT-MARTIN-(FR)', '', 'CONTINENT02COUNTRY044', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-MARTIN', 'SAINT-MARTIN', '', 'CONTINENT02COUNTRY045', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-PIERRE-ET-MIQUELON', 'SAINT-PIERRE-ET-MIQUELON', '', 'CONTINENT02COUNTRY046', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-VINCENT-AND-THE-GRENADINES', 'SAINT-VINCENT-ET-LES-GRENADINES', '', 'CONTINENT02COUNTRY047', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SALVADOR', 'SALVADOR', '', 'CONTINENT02COUNTRY048', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'SURINAME', 'SURINAME', '', 'CONTINENT02COUNTRY049', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'TRINIDAD-AND-TOBAGO', 'TRINITÉ-ET-TOBAGO', '', 'CONTINENT02COUNTRY050', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'URUGUAY', 'URUGUAY', '', 'CONTINENT02COUNTRY051', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'VENEZUELA', 'VENEZUELA', '', 'CONTINENT02COUNTRY052', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'VIRGIN-AMERICAN-WOMEN', 'VIERGES-AMÉRICAINES', '', 'CONTINENT02COUNTRY053', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'BRITISH-VIRGIN-ISLANDS', 'VIERGES-BRITANNIQUES', '', 'CONTINENT02COUNTRY054', 'CONTINENT02');
INSERT INTO DDVS VALUES ('COUNTRY', 'AFGHANISTAN', 'AFGHANISTAN', '', 'CONTINENT03COUNTRY001', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'ARABIA-SAOUDITE', 'ARABIE-SAOUDITE', '', 'CONTINENT03COUNTRY002', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'BAHRAIN', 'BAHREÏN', '', 'CONTINENT03COUNTRY003', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'BANGLADESH', 'BANGLADESH', '', 'CONTINENT03COUNTRY004', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'BHUTAN', 'BHOUTAN', '', 'CONTINENT03COUNTRY005', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'BURMA', 'BIRMANIE', '', 'CONTINENT03COUNTRY006', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'BRUNEI', 'BRUNEI', '', 'CONTINENT03COUNTRY007', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'CAMBODIA', 'CAMBODGE', '', 'CONTINENT03COUNTRY008', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'CHINA', 'CHINE', '', 'CONTINENT03COUNTRY009', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'NORTH-KOREA', 'CORÉE-DU-NORD', '', 'CONTINENT03COUNTRY010', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'SOUTH-KOREA', 'CORÉE-DU-SUD', '', 'CONTINENT03COUNTRY011', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'UNITED-ARAB-EMIRATES', 'ÉMIRATS-ARABES-UNIS', '', 'CONTINENT03COUNTRY012', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'HONG-KONG', 'HONG-KONG', '', 'CONTINENT03COUNTRY013', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'INDIA', 'INDE', '', 'CONTINENT03COUNTRY014', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'INDONESIA', 'INDONÉSIE', '', 'CONTINENT03COUNTRY015', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'IRAQ', 'IRAK', '', 'CONTINENT03COUNTRY016', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'IRAN', 'IRAN', '', 'CONTINENT03COUNTRY017', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'ISRAEL', 'ISRAËL', '', 'CONTINENT03COUNTRY018', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'JAPAN', 'JAPON', '', 'CONTINENT03COUNTRY019', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'JORDAN', 'JORDANIE', '', 'CONTINENT03COUNTRY020', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'KAZAKHSTAN', 'KAZAKHSTAN', '', 'CONTINENT03COUNTRY021', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'KIRGHIZISTAN', 'KIRGHIZISTAN', '', 'CONTINENT03COUNTRY022', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'KOWEIT', 'KOWEÏT', '', 'CONTINENT03COUNTRY023', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'LAOS', 'LAOS', '', 'CONTINENT03COUNTRY024', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'LEBANON', 'LIBAN', '', 'CONTINENT03COUNTRY025', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'MACAO', 'MACAO', '', 'CONTINENT03COUNTRY026', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'MALAYSIS', 'MALAISIE', '', 'CONTINENT03COUNTRY027', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'MALDIVES', 'MALDIVES', '', 'CONTINENT03COUNTRY028', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'MONGOLY', 'MONGOLIE', '', 'CONTINENT03COUNTRY029', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'NÉPAL', 'NÉPAL', '', 'CONTINENT03COUNTRY030', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'OMAN', 'OMAN', '', 'CONTINENT03COUNTRY031', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'UZBEKISTAN', 'OUZBÉKISTAN', '', 'CONTINENT03COUNTRY032', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'PAKISTAN', 'PAKISTAN', '', 'CONTINENT03COUNTRY033', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'PALESTINE', 'PALESTINE', '', 'CONTINENT03COUNTRY034', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'PHILIPPINES', 'PHILIPPINES', '', 'CONTINENT03COUNTRY035', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'QATAR', 'QATAR', '', 'CONTINENT03COUNTRY036', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'SINGAPORE', 'SINGAPOUR', '', 'CONTINENT03COUNTRY037', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'SRI-LANKA', 'SRI-LANKA', '', 'CONTINENT03COUNTRY038', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'SYRIA', 'SYRIE', '', 'CONTINENT03COUNTRY039', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'TADJIKISTAN', 'TADJIKISTAN', '', 'CONTINENT03COUNTRY040', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'TAIWAN', 'TAIWAN', '', 'CONTINENT03COUNTRY041', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'THAILAND', 'THAÏLANDE', '', 'CONTINENT03COUNTRY042', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'TURKMENISTAN', 'TURKMÉNISTAN', '', 'CONTINENT03COUNTRY043', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'VIÊT-NAM', 'VIÊT-NAM', '', 'CONTINENT03COUNTRY044', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'YEMEN', 'YÉMEN', '', 'CONTINENT03COUNTRY045', 'CONTINENT03');
INSERT INTO DDVS VALUES ('COUNTRY', 'ALBANIA', 'ALBANIE', '', 'CONTINENT04COUNTRY001', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'GERMANY', 'ALLEMAGNE', '', 'CONTINENT04COUNTRY002', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'ANDORRA', 'ANDORRE', '', 'CONTINENT04COUNTRY003', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'ARMENIA', 'ARMÉNIE', '', 'CONTINENT04COUNTRY004', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'AUSTRIA', 'AUTRICHE', '', 'CONTINENT04COUNTRY005', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'BALEAARES', 'BALÉARES', '', 'CONTINENT04COUNTRY006', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'BELGIUM', 'BELGIQUE', '', 'CONTINENT04COUNTRY007', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'BELARUSSY', 'BIÉLORUSSIE', '', 'CONTINENT04COUNTRY008', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'BOSNIA', 'BOSNIE', '', 'CONTINENT04COUNTRY009', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'BOSNIA-HERZEGOVINA', 'BOSNIE-HERZÉGOVINE', '', 'CONTINENT04COUNTRY010', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'BULGARIA', 'BULGARIE', '', 'CONTINENT04COUNTRY011', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'CYPRUS', 'CHYPRE', '', 'CONTINENT04COUNTRY012', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'CRIMED', 'CRIMÉE', '', 'CONTINENT04COUNTRY013', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'CROATIA', 'CROATIE', '', 'CONTINENT04COUNTRY014', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'DENMARK', 'DANEMARK', '', 'CONTINENT04COUNTRY015', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SPAIN', 'ESPAGNE', '', 'CONTINENT04COUNTRY016', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'ESTONIA', 'ESTONIE', '', 'CONTINENT04COUNTRY017', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'FARROE', 'FÉROÉ', '', 'CONTINENT04COUNTRY018', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'FINLAND', 'FINLANDE', '', 'CONTINENT04COUNTRY019', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'FRANCE', 'FRANCE', '', 'CONTINENT04COUNTRY020', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'GEORGIA', 'GÉORGIE', '', 'CONTINENT04COUNTRY021', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'GIBRALTAR', 'GIBRALTAR', '', 'CONTINENT04COUNTRY022', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'GREECE', 'GRÈCE', '', 'CONTINENT04COUNTRY023', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'HUNGARY', 'HONGRIE', '', 'CONTINENT04COUNTRY024', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'IRELAND', 'IRLANDE', '', 'CONTINENT04COUNTRY025', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'ICELAND', 'ISLANDE', '', 'CONTINENT04COUNTRY026', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'ITALY', 'ITALIE', '', 'CONTINENT04COUNTRY027', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'KOSOVO', 'KOSOVO', '', 'CONTINENT04COUNTRY028', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'LATVIA', 'LETTONIE', '', 'CONTINENT04COUNTRY029', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'LIECHTENSTEIN', 'LIECHTENSTEIN', '', 'CONTINENT04COUNTRY030', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'LITHUANIA', 'LITUANIE', '', 'CONTINENT04COUNTRY031', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'LUXEMBOURG', 'LUXEMBOURG', '', 'CONTINENT04COUNTRY032', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'MACEDOIN', 'MACÉDOINE', '', 'CONTINENT04COUNTRY033', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'MALTA', 'MALTE', '', 'CONTINENT04COUNTRY034', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'MOLDAVIA', 'MOLDAVIE', '', 'CONTINENT04COUNTRY035', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'MONACO', 'MONACO', '', 'CONTINENT04COUNTRY036', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'MONTENEGRO', 'MONTÉNÉGRO', '', 'CONTINENT04COUNTRY037', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'NORWAY', 'NORVÈGE', '', 'CONTINENT04COUNTRY038', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'NETHERLANDS', 'PAYS-BAS', '', 'CONTINENT04COUNTRY039', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'POLAND', 'POLOGNE', '', 'CONTINENT04COUNTRY040', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'PORTUGAL', 'PORTUGAL', '', 'CONTINENT04COUNTRY041', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'CZECH-REPUBLIC', 'RÉPUBLIQUE-TCHÈQUE', '', 'CONTINENT04COUNTRY042', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'ROMANIA', 'ROUMANIE', '', 'CONTINENT04COUNTRY043', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'UNITED-KINGDOM', 'ROYAUME-UNI', '', 'CONTINENT04COUNTRY044', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'RUSSIA', 'RUSSIE', '', 'CONTINENT04COUNTRY045', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAINT-MARINE', 'SAINT-MARIN', '', 'CONTINENT04COUNTRY046', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SERBIA', 'SERBIE', '', 'CONTINENT04COUNTRY047', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SLOVAKIA', 'SLOVAQUIE', '', 'CONTINENT04COUNTRY048', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SLOVENIA', 'SLOVÉNIE', '', 'CONTINENT04COUNTRY049', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SWEDEN', 'SUÈDE', '', 'CONTINENT04COUNTRY050', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'SWITZERLAND', 'SUISSE', '', 'CONTINENT04COUNTRY051', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'TURKEY', 'TURQUIE', '', 'CONTINENT04COUNTRY052', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'UKRAINE', 'UKRAINE', '', 'CONTINENT04COUNTRY053', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'VATICAN', 'VATICAN', '', 'CONTINENT04COUNTRY054', 'CONTINENT04');
INSERT INTO DDVS VALUES ('COUNTRY', 'AUSTRALIA', 'AUSTRALIE', '', 'CONTINENT05COUNTRY001', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'CHRISTMAS', 'CHRISTMAS', '', 'CONTINENT05COUNTRY002', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'COCO', 'COCO', '', 'CONTINENT05COUNTRY003', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'FIDJI', 'FIDJI', '', 'CONTINENT05COUNTRY004', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'GUAM', 'GUAM', '', 'CONTINENT05COUNTRY005', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'HAWAY', 'HAWAÏ', '', 'CONTINENT05COUNTRY006', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'KIRIBATI', 'KIRIBATI', '', 'CONTINENT05COUNTRY007', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'MARIANNE', 'MARIANNE', '', 'CONTINENT05COUNTRY008', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'MARSHALL', 'MARSHALL', '', 'CONTINENT05COUNTRY009', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'MICRONESIA', 'MICRONÉSIE', '', 'CONTINENT05COUNTRY010', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'NAURU ', 'NAURU ', '', 'CONTINENT05COUNTRY011', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'NIUE', 'NIUE', '', 'CONTINENT05COUNTRY012', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'NORFOLK', 'NORFOLK', '', 'CONTINENT05COUNTRY013', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'NEW-CALEDONIA', 'NOUVELLE-CALÉDONIE', '', 'CONTINENT05COUNTRY014', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'NEW-ZEALAND', 'NOUVELLE-ZÉLANDE', '', 'CONTINENT05COUNTRY015', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'PALAU', 'PALAU', '', 'CONTINENT05COUNTRY016', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'PAPUA-NEW-GUINEA', 'PAPOUASIE-NOUVELLE-GUINÉE', '', 'CONTINENT05COUNTRY017', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'EASTERN', 'PÂQUES', '', 'CONTINENT05COUNTRY018', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'PITCAIRN', 'PITCAIRN', '', 'CONTINENT05COUNTRY019', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'POLYNESIA-FRENCH', 'POLYNÉSIE-FRANÇAISE', '', 'CONTINENT05COUNTRY020', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'SALOMON', 'SALOMON', '', 'CONTINENT05COUNTRY021', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAMOA', 'SAMOA', '', 'CONTINENT05COUNTRY022', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'SAMOA-AMERICANA', 'SAMOA-AMÉRICAINES', '', 'CONTINENT05COUNTRY023', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'TONGA', 'TONGA', '', 'CONTINENT05COUNTRY024', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'TUVALU', 'TUVALU', '', 'CONTINENT05COUNTRY025', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'VANUATED', 'VANUATU', '', 'CONTINENT05COUNTRY026', 'CONTINENT05');
INSERT INTO DDVS VALUES ('COUNTRY', 'WALLIS-AND-FUTUNA', 'WALLIS-ET-FUTUNA', '', 'CONTINENT05COUNTRY027', 'CONTINENT05');
COMMIT;
INSERT INTO DDVS VALUES ('CITY', 'CHALONS-EN-CHAMPAGNE', 'CHALONS-EN-CHAMPAGNE', '', 'FRCITY_00001', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NICE', 'NICE', '', 'FRCITY_00002', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'AIX-EN-PROVENCE', 'AIX-EN-PROVENCE', '', 'FRCITY_00003', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CAEN', 'CAEN', '', 'FRCITY_00004', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BOURGES', 'BOURGES', '', 'FRCITY_00005', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'DIJON', 'DIJON', '', 'FRCITY_00006', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BREST', 'BREST', '', 'FRCITY_00007', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TOULOUSE', 'TOULOUSE', '', 'FRCITY_00008', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PESSAC', 'PESSAC', '', 'FRCITY_00009', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MONTPELLIER', 'MONTPELLIER', '', 'FRCITY_00010', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'RENNES', 'RENNES', '', 'FRCITY_00011', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-ETIENNE', 'SAINT-ETIENNE', '', 'FRCITY_00012', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ANGERS', 'ANGERS', '', 'FRCITY_00013', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'REIMS', 'REIMS', '', 'FRCITY_00014', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LORIENT', 'LORIENT', '', 'FRCITY_00015', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'METZ', 'METZ', '', 'FRCITY_00016', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LILLE', 'LILLE', '', 'FRCITY_00017', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ROUBAIX', 'ROUBAIX', '', 'FRCITY_00018', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'DUNKERQUE', 'DUNKERQUE', '', 'FRCITY_00019', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'VILLENEUVE-D-ASCQ', 'VILLENEUVE-D-ASCQ', '', 'FRCITY_00020', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'COMPIEGNE', 'COMPIEGNE', '', 'FRCITY_00021', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ARRAS', 'ARRAS', '', 'FRCITY_00022', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'AUBIERE', 'AUBIERE', '', 'FRCITY_00023', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'STRASBOURG', 'STRASBOURG', '', 'FRCITY_00024', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LYON', 'LYON', '', 'FRCITY_00025', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'VILLEURBANNE', 'VILLEURBANNE', '', 'FRCITY_00026', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'VAULX-EN-VELIN', 'VAULX-EN-VELIN', '', 'FRCITY_00027', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PARIS', 'PARIS', '', 'FRCITY_00028', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TOULON', 'TOULON', '', 'FRCITY_00029', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PALAISEAU', 'PALAISEAU', '', 'FRCITY_00030', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-DENIS', 'SAINT-DENIS', '', 'FRCITY_00031', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-DENIS-LA-PLAINE', 'SAINT-DENIS-LA-PLAINE', '', 'FRCITY_00032', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MAISONS-ALFORT', 'MAISONS-ALFORT', '', 'FRCITY_00033', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ARCUEIL', 'ARCUEIL', '', 'FRCITY_00034', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NOUMEA', 'NOUMEA', '', 'FRCITY_00035', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'FAAA', 'FAAA', '', 'FRCITY_00036', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MARSEILLE', 'MARSEILLE', '', 'FRCITY_00037', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LA-ROCHELLE', 'LA-ROCHELLE', '', 'FRCITY_00038', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TALENCE', 'TALENCE', '', 'FRCITY_00039', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BRUZ', 'BRUZ', '', 'FRCITY_00040', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'GRENOBLE', 'GRENOBLE', '', 'FRCITY_00041', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ORLEANS', 'ORLEANS', '', 'FRCITY_00042', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CLERMONT-FERRAND', 'CLERMONT-FERRAND', '', 'FRCITY_00043', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MARCY-L-ETOILE', 'MARCY-L-ETOILE', '', 'FRCITY_00044', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ECULLY', 'ECULLY', '', 'FRCITY_00045', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MONT-SAINT-AIGNAN', 'MONT-SAINT-AIGNAN', '', 'FRCITY_00046', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LE-HAVRE', 'LE-HAVRE', '', 'FRCITY_00047', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'FONTAINEBLEAU', 'FONTAINEBLEAU', '', 'FRCITY_00048', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MONTIGNY-LE-BRETONNEUX', 'MONTIGNY-LE-BRETONNEUX', '', 'FRCITY_00049', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'AMIENS', 'AMIENS', '', 'FRCITY_00050', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ALBI', 'ALBI', '', 'FRCITY_00051', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'AVIGNON', 'AVIGNON', '', 'FRCITY_00052', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CHASSENEUIL', 'CHASSENEUIL', '', 'FRCITY_00053', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'POITIERS', 'POITIERS', '', 'FRCITY_00054', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SEVRES', 'SEVRES', '', 'FRCITY_00055', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NANTERRE', 'NANTERRE', '', 'FRCITY_00056', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-OUEN', 'SAINT-OUEN', '', 'FRCITY_00057', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CACHAN', 'CACHAN', '', 'FRCITY_00058', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CERGY', 'CERGY', '', 'FRCITY_00059', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CERGY-PONTOISE', 'CERGY-PONTOISE', '', 'FRCITY_00060', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CORTE', 'CORTE', '', 'FRCITY_00061', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CAYENNE', 'CAYENNE', '', 'FRCITY_00062', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-DENIS-MESSAG', 'SAINT-DENIS-MESSAG', '', 'FRCITY_00063', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SALON-AIR', 'SALON-AIR', '', 'FRCITY_00064', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TROYES', 'TROYES', '', 'FRCITY_00065', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'EPRON', 'EPRON', '', 'FRCITY_00066', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BESANCON', 'BESANCON', '', 'FRCITY_00067', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BORDEAUX', 'BORDEAUX', '', 'FRCITY_00068', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TOURS', 'TOURS', '', 'FRCITY_00069', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-MARTIN-D-HERES', 'SAINT-MARTIN-D-HERES', '', 'FRCITY_00070', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NANTES', 'NANTES', '', 'FRCITY_00071', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LES-PONTS-DE-CE', 'LES-PONTS-DE-CE', '', 'FRCITY_00072', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-BARTHELEMY-D-ANJOU', 'SAINT-BARTHELEMY-D-ANJOU', '', 'FRCITY_00073', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NANCY', 'NANCY', '', 'FRCITY_00074', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BEAUVAIS', 'BEAUVAIS', '', 'FRCITY_00075', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PAU-UNIVERSITE', 'PAU-UNIVERSITE', '', 'FRCITY_00076', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PERPIGNAN', 'PERPIGNAN', '', 'FRCITY_00077', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LE-MANS', 'LE-MANS', '', 'FRCITY_00078', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CHAMPS-SUR-MARNE', 'CHAMPS-SUR-MARNE', '', 'FRCITY_00079', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'VERSAILLES', 'VERSAILLES', '', 'FRCITY_00080', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LIMOGES', 'LIMOGES', '', 'FRCITY_00081', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ORSAY', 'ORSAY', '', 'FRCITY_00082', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'EVRY', 'EVRY', '', 'FRCITY_00083', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SCEAUX', 'SCEAUX', '', 'FRCITY_00084', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PARIS-LA-DÉFENSE', 'PARIS-LA-DÉFENSE', '', 'FRCITY_00085', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'PONTOISE', 'PONTOISE', '', 'FRCITY_00086', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'GRADIGNAN', 'GRADIGNAN', '', 'FRCITY_00087', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'EURALILLE', 'EURALILLE', '', 'FRCITY_00088', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'BAYONNE', 'BAYONNE', '', 'FRCITY_00089', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MULHOUSE', 'MULHOUSE', '', 'FRCITY_00090', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'DARNETAL', 'DARNETAL', '', 'FRCITY_00091', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-ETIENNE-DU-ROUVRAY', 'SAINT-ETIENNE-DU-ROUVRAY', '', 'FRCITY_00092', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MARNE-LA-VALLEE', 'MARNE-LA-VALLEE', '', 'FRCITY_00093', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CRETEIL', 'CRETEIL', '', 'FRCITY_00094', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'JOUY-EN-JOSAS', 'JOUY-EN-JOSAS', '', 'FRCITY_00095', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SEVENANS', 'SEVENANS', '', 'FRCITY_00096', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SURESNES', 'SURESNES', '', 'FRCITY_00097', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NOISY-LE-GRAND', 'NOISY-LE-GRAND', '', 'FRCITY_00098', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'DEMBENI', 'DEMBENI', '', 'FRCITY_00099', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'MOUGINS', 'MOUGINS', '', 'FRCITY_00100', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CAGNES-SUR-MER', 'CAGNES-SUR-MER', '', 'FRCITY_00101', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'NIMES', 'NIMES', '', 'FRCITY_00102', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CASTANET-TOLOSAN', 'CASTANET-TOLOSAN', '', 'FRCITY_00103', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'AULNOY-LEZ-VALENCIENNES', 'AULNOY-LEZ-VALENCIENNES', '', 'FRCITY_00104', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TARBES', 'TARBES', '', 'FRCITY_00105', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'CHAMBERY', 'CHAMBERY', '', 'FRCITY_00106', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-ETIENNE-ROUVRAY', 'SAINT-ETIENNE-ROUVRAY', '', 'FRCITY_00107', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'ROUEN', 'ROUEN', '', 'FRCITY_00108', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'LA-ROCHE-SUR-YON', 'LA-ROCHE-SUR-YON', '', 'FRCITY_00109', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'SAINT-AUBIN', 'SAINT-AUBIN', '', 'FRCITY_00110', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'GIF-SUR-YVETTE', 'GIF-SUR-YVETTE', '', 'FRCITY_00111', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'VILLETANEUSE', 'VILLETANEUSE', '', 'FRCITY_00112', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'VILLEJUIF', 'VILLEJUIF', '', 'FRCITY_00113', 'CONTINENT04COUNTRY020');
INSERT INTO DDVS VALUES ('CITY', 'TUNIS', 'TUNIS', '', 'TNCITY_00001', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'MATEUR', 'MATEUR', '', 'TNCITY_00002', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'SOUSSE', 'SOUSSE', '', 'TNCITY_00003', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'SFAX', 'SFAX', '', 'TNCITY_00004', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'BIZERTE', 'BIZERTE', '', 'TNCITY_00005', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'NABEUL', 'NABEUL', '', 'TNCITY_00006', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'HAMMAMET', 'HAMMAMET', '', 'TNCITY_00007', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'MONASTIR', 'MONASTIR', '', 'TNCITY_00008', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'BEJA', 'BEJA', '', 'TNCITY_00009', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'DJERBA', 'DJERBA', '', 'TNCITY_00010', 'CONTINENT01COUNTRY048');
INSERT INTO DDVS VALUES ('CITY', 'LONDON', 'LONDRES', '', 'UKCITY_00001', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'SHEFFIELDS', 'CHEFFIELDS', '', 'UKCITY_00002', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'BRISTOL', 'BRISTOL', '', 'UKCITY_00003', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'LEEDS', 'LEEDS', '', 'UKCITY_00004', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'EDIMBOURG', 'EDIMBOURG', '', 'UKCITY_00005', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'CARDIFF', 'CARDIFF', '', 'UKCITY_00006', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'STROKE', 'STROKE', '', 'UKCITY_00007', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'KINGSTON', 'KINGSTON', '', 'UKCITY_00008', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'BELFAST', 'BELFAST', '', 'UKCITY_00009', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'BRADFORD', 'BRADFORD', '', 'UKCITY_00010', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'COVENTRY', 'COVENTRY', '', 'UKCITY_00011', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'NEWCASTLE', 'NEWCASTLE', '', 'UKCITY_00012', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'PLYMOUTH', 'PLYMOUTH', '', 'UKCITY_00013', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'SOUTHAMPTON', 'SOUTHAMPTON', '', 'UKCITY_00014', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'LECEISTER', 'LECEISTER', '', 'UKCITY_00015', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'BIRMINGHAM', 'BIRMINGHAM', '', 'UKCITY_00016', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'GLASGOW', 'GLASGOW', '', 'UKCITY_00017', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'READING', 'READING', '', 'UKCITY_00018', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'MANCHESTER', 'MANCHESTER', '', 'UKCITY_00019', 'CONTINENT04COUNTRY044');
INSERT INTO DDVS VALUES ('CITY', 'BEIJING', 'PÉKIN', '', 'CHCITY_00001', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'SHANGHAI', 'SHANGHAI', '', 'CHCITY_00002', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'CANTON', 'CANTON', '', 'CHCITY_00004', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'SHENZHEN', 'SHENZHEN', '', 'CHCITY_00005', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'DONGGUAN', 'DONGGUAN', '', 'CHCITY_00006', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'TIANJIN', 'TIANJIN', '', 'CHCITY_00007', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'HONG KONG', 'HONG KONG', '', 'CHCITY_00008', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'WUHAN', 'WUHAN', '', 'CHCITY_00009', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'SHENYANG', 'SHENYANG', '', 'CHCITY_00010', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'NANKIN', 'NANKIN', '', 'CHCITY_00011', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'CHONGQING', 'CHONGQING', '', 'CHCITY_00012', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'CHENGDU', 'CHENGDU', '', 'CHCITY_00013', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'HANGZHOU', 'HANGZHOU', '', 'CHCITY_00014', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'XI''AN', 'XI''AN', '', 'CHCITY_00015', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'QINGDAO', 'QINGDAO', '', 'CHCITY_00016', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'HARBIN', 'HARBIN', '', 'CHCITY_00017', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'CHANGCHUN', 'CHANGCHUN', '', 'CHCITY_00018', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'CHANGSHA', 'CHANGSHA', '', 'CHCITY_00019', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'NANCHANG', 'NANCHANG', '', 'CHCITY_00020', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'SHIJIAZHUANG', 'SHIJIAZHUANG', '', 'CHCITY_00021', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'DALIAN', 'DALIEN', '', 'CHCITY_00022', 'CONTINENT03COUNTRY009');
INSERT INTO DDVS VALUES ('CITY', 'JINAN', 'JINAN', '', 'CHCITY_00023', 'CONTINENT03COUNTRY009');
COMMIT;

